# Generated by Django 5.2.8 on 2025-12-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='store_service_type',
            field=models.CharField(blank=True, choices=[('barber', 'Barbería'), ('beauty_salon', 'Salón de belleza'), ('nails', 'Uñas'), ('spa', 'Spa'), ('massage', 'Masajes'), ('clinic', 'Clínica'), ('personal_trainer', 'Entrenador personal')], max_length=30),
        ),
    ]
