# Generated by Django 5.2.8 on 2025-11-19 22:26

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='handled_at',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 22, 23, 17, 186745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='contact_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='contact_phone',
            field=models.CharField(default='00000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='store_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('provider', 'Proveedor / Tienda')], default='client', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
