# Generated by Django 5.2.8 on 2025-11-19 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_providerapplication_handled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 22, 26, 56, 72203, tzinfo=datetime.timezone.utc)),
        ),
    ]
