# Generated by Django 5.2.8 on 2025-11-19 22:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_providerapplication_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.ProviderApplication.default_expiry),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
