# Generated by Django 5.2.8 on 2025-11-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_providerapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
